### ISSUE TITLE
Unsafe tempfile handling

### ISSUE THREAD

**Issue by tv42** [ShoshinNikita/go-disk-buffer#1]
This is not safe. Tempfiles need to be created with O_EXCL. Use https://golang.org/pkg/io/ioutil/#TempFile instead of this buggy code.

https://github.com/ShoshinNikita/go-disk-buffer/blob/a0e607a0a94575ecd68b1dc30669817924794449/buffer.go#L114-L115

```
	b.filename = os.TempDir() + "/" + generateRandomString(tempFilenameLength) + ".tmp"
	b.file, err = os.Create(b.filename)
```

**Comment by ShoshinNikita** [comment]
Thank you for your remark! I didn't know about `ioutil.TempFile()` function before.

I fixed it in 996d424d9465373fe405ca7f48d1ac8ea3e339b3
