### ISSUE TITLE
Add disk encryption

### ISSUE THREAD

**Issue by mschneider82** [ShoshinNikita/go-disk-buffer#2]
Hi,

It would be nice to add optional encryption/decryption. So only the data which is Written and Read from Disk is encrypted (not the in-memory part).

What do you think?

Best Regards

**Comment by ShoshinNikita** [comment]
Thank you for the suggestion. It is an interesting idea, but I have some questions.

- Why we should encrypt data only on a disk? I think, it's not very difficult to get the data from RAM too.
- Why not to use [minio/sio](https://github.com/minio/sio) for encryption?

I just think the package `go-disk-buffer` should have only a single responsibility – storing data on a disk when `bytes.Buffer` is overflowed

**Comment by mschneider82** [comment]
Data in memory is classified as "Data In Use/Transit" https://en.wikipedia.org/wiki/Data_in_use
Data on disk is classified as "Data At Rest" (may needs encryption)

Thats why it would be nice to have a optional encryption function for the "data at rest".

If you for example process alot of mails to the Buffer, most mails are small and doesnt need encryption in memory, but if you store them to disk a encryption is usefull

If memory is not safe i would recommend github.com/awnumar/memguard
